version: "3"

services:
  web:
    build: .
    container_name: self-dining-web
    command: poetry run python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/web
    depends_on:
      - db
  db:
    image: postgres
    container_name: self-dining-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
  
volumes:
  postgres_db: